import { FashionItem, Category, StyleType, BodyType, GenderExpression } from "@/types/fashion";

// In-memory fashion catalog — works on serverless (Vercel) without SQLite
export const catalogItems: FashionItem[] = [
  // === TOPS ===
  { id: "top-001", name: "Classic White Oxford Shirt", category: Category.TOP, subcategory: "button-down", colors: ["#FFFFFF", "#F5F5F5"], dominantColor: "#FFFFFF", styles: [StyleType.CLASSIC, StyleType.PREPPY, StyleType.MINIMALIST, StyleType.SMART_CASUAL], priceUsd: 55, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/tops/button-down.png", fitType: "regular", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "cotton", season: ["spring", "summer", "fall", "winter"], minimalAesthetic: true, genderExpression: GenderExpression.NEUTRAL },
  { id: "top-002", name: "Navy Crew Neck T-Shirt", category: Category.TOP, subcategory: "t-shirt", colors: ["#1B3A5C"], dominantColor: "#1B3A5C", styles: [StyleType.MINIMALIST, StyleType.STREETWEAR, StyleType.SMART_CASUAL], priceUsd: 25, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/tops/t-shirt.png", fitType: "slim", bodyTypeCompatibility: [BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE, BodyType.HOURGLASS], material: "cotton", season: ["spring", "summer", "fall"], minimalAesthetic: true, genderExpression: GenderExpression.MASCULINE },
  { id: "top-003", name: "Floral Wrap Blouse", category: Category.TOP, subcategory: "blouse", colors: ["#E8A0BF", "#2D5F2D", "#FFFFFF"], dominantColor: "#E8A0BF", styles: [StyleType.ROMANTIC, StyleType.BOHEMIAN], priceUsd: 42, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/tops/blouse.png", fitType: "relaxed", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS], material: "viscose", season: ["spring", "summer"], minimalAesthetic: false, genderExpression: GenderExpression.FEMININE },
  { id: "top-004", name: "Black Turtleneck Sweater", category: Category.TOP, subcategory: "sweater", colors: ["#1A1A1A"], dominantColor: "#1A1A1A", styles: [StyleType.MINIMALIST, StyleType.CLASSIC, StyleType.EDGY, StyleType.SMART_CASUAL], priceUsd: 68, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/tops/sweater.png", fitType: "slim", bodyTypeCompatibility: [BodyType.RECTANGLE, BodyType.HOURGLASS, BodyType.INVERTED_TRIANGLE, BodyType.PEAR], material: "merino wool", season: ["fall", "winter"], minimalAesthetic: true, genderExpression: GenderExpression.NEUTRAL },
  { id: "top-005", name: "Oversized Graphic Hoodie", category: Category.TOP, subcategory: "hoodie", colors: ["#808080", "#FF4500"], dominantColor: "#808080", styles: [StyleType.STREETWEAR, StyleType.ATHLEISURE], priceUsd: 60, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/tops/hoodie.png", fitType: "oversized", bodyTypeCompatibility: [BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE, BodyType.APPLE], material: "cotton blend", season: ["fall", "winter", "spring"], minimalAesthetic: false, genderExpression: GenderExpression.NEUTRAL },
  { id: "top-006", name: "Sage Linen Camp Collar Shirt", category: Category.TOP, subcategory: "camp-collar", colors: ["#9CAF88"], dominantColor: "#9CAF88", styles: [StyleType.MINIMALIST, StyleType.BOHEMIAN, StyleType.SMART_CASUAL], priceUsd: 48, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/tops/camp-collar.png", fitType: "relaxed", bodyTypeCompatibility: [BodyType.APPLE, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "linen", season: ["spring", "summer"], minimalAesthetic: true, genderExpression: GenderExpression.MASCULINE },
  { id: "top-007", name: "Burgundy Silk Camisole", category: Category.TOP, subcategory: "camisole", colors: ["#722F37"], dominantColor: "#722F37", styles: [StyleType.ROMANTIC, StyleType.CLASSIC, StyleType.EDGY], priceUsd: 55, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/tops/camisole.png", fitType: "slim", bodyTypeCompatibility: [BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.PEAR], material: "silk", season: ["spring", "summer", "fall"], minimalAesthetic: true, genderExpression: GenderExpression.FEMININE },

  // === BOTTOMS ===
  { id: "bot-001", name: "Dark Indigo Straight Jeans", category: Category.BOTTOM, subcategory: "jeans", colors: ["#1C1C3A"], dominantColor: "#1C1C3A", styles: [StyleType.CLASSIC, StyleType.STREETWEAR, StyleType.MINIMALIST, StyleType.SMART_CASUAL], priceUsd: 75, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/bottoms/jeans.png", fitType: "straight", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "denim", season: ["spring", "summer", "fall", "winter"], minimalAesthetic: true, genderExpression: GenderExpression.NEUTRAL },
  { id: "bot-002", name: "Olive Cargo Pants", category: Category.BOTTOM, subcategory: "cargo", colors: ["#556B2F"], dominantColor: "#556B2F", styles: [StyleType.STREETWEAR, StyleType.ATHLEISURE], priceUsd: 65, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/bottoms/cargo.png", fitType: "relaxed", bodyTypeCompatibility: [BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE, BodyType.APPLE], material: "cotton twill", season: ["spring", "fall", "winter"], minimalAesthetic: false, genderExpression: GenderExpression.MASCULINE },
  { id: "bot-003", name: "Camel Wide-Leg Trousers", category: Category.BOTTOM, subcategory: "trousers", colors: ["#C19A6B"], dominantColor: "#C19A6B", styles: [StyleType.CLASSIC, StyleType.MINIMALIST, StyleType.SMART_CASUAL, StyleType.BOHEMIAN], priceUsd: 85, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/bottoms/trousers.png", fitType: "wide-leg", bodyTypeCompatibility: [BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE], material: "wool blend", season: ["fall", "winter", "spring"], minimalAesthetic: true, genderExpression: GenderExpression.FEMININE },
  { id: "bot-004", name: "Black Tailored Chinos", category: Category.BOTTOM, subcategory: "chinos", colors: ["#1A1A1A"], dominantColor: "#1A1A1A", styles: [StyleType.CLASSIC, StyleType.SMART_CASUAL, StyleType.MINIMALIST], priceUsd: 60, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/bottoms/chinos.png", fitType: "slim", bodyTypeCompatibility: [BodyType.RECTANGLE, BodyType.HOURGLASS, BodyType.INVERTED_TRIANGLE], material: "cotton stretch", season: ["spring", "summer", "fall", "winter"], minimalAesthetic: true, genderExpression: GenderExpression.NEUTRAL },
  { id: "bot-005", name: "Cream Pleated Midi Skirt", category: Category.BOTTOM, subcategory: "skirt", colors: ["#FFFDD0"], dominantColor: "#FFFDD0", styles: [StyleType.CLASSIC, StyleType.ROMANTIC, StyleType.MINIMALIST], priceUsd: 58, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/bottoms/skirt.png", fitType: "a-line", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE], material: "polyester blend", season: ["spring", "summer"], minimalAesthetic: true, genderExpression: GenderExpression.FEMININE },

  // === DRESSES ===
  { id: "drs-001", name: "Black Wrap Midi Dress", category: Category.DRESS, subcategory: "wrap-dress", colors: ["#1A1A1A"], dominantColor: "#1A1A1A", styles: [StyleType.CLASSIC, StyleType.SMART_CASUAL, StyleType.MINIMALIST], priceUsd: 95, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/dresses/wrap-dress.png", fitType: "wrap", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "jersey", season: ["spring", "summer", "fall"], minimalAesthetic: true, genderExpression: GenderExpression.FEMININE },
  { id: "drs-002", name: "Terracotta Linen Shirt Dress", category: Category.DRESS, subcategory: "shirt-dress", colors: ["#CC6B49"], dominantColor: "#CC6B49", styles: [StyleType.BOHEMIAN, StyleType.CLASSIC, StyleType.SMART_CASUAL], priceUsd: 78, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/dresses/shirt-dress.png", fitType: "relaxed", bodyTypeCompatibility: [BodyType.APPLE, BodyType.RECTANGLE, BodyType.PEAR], material: "linen", season: ["spring", "summer"], minimalAesthetic: true, genderExpression: GenderExpression.FEMININE },

  // === OUTERWEAR ===
  { id: "out-001", name: "Camel Wool Overcoat", category: Category.OUTERWEAR, subcategory: "overcoat", colors: ["#C19A6B"], dominantColor: "#C19A6B", styles: [StyleType.CLASSIC, StyleType.MINIMALIST, StyleType.SMART_CASUAL], priceUsd: 195, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/outerwear/overcoat.png", fitType: "structured", bodyTypeCompatibility: [BodyType.RECTANGLE, BodyType.HOURGLASS, BodyType.INVERTED_TRIANGLE], material: "wool", season: ["fall", "winter"], minimalAesthetic: true, genderExpression: GenderExpression.NEUTRAL },
  { id: "out-002", name: "Black Leather Biker Jacket", category: Category.OUTERWEAR, subcategory: "biker-jacket", colors: ["#1A1A1A"], dominantColor: "#1A1A1A", styles: [StyleType.EDGY, StyleType.STREETWEAR], priceUsd: 180, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/outerwear/biker-jacket.png", fitType: "slim", bodyTypeCompatibility: [BodyType.RECTANGLE, BodyType.HOURGLASS, BodyType.INVERTED_TRIANGLE], material: "leather", season: ["fall", "winter", "spring"], minimalAesthetic: false, genderExpression: GenderExpression.NEUTRAL },
  { id: "out-003", name: "Olive Bomber Jacket", category: Category.OUTERWEAR, subcategory: "bomber", colors: ["#556B2F"], dominantColor: "#556B2F", styles: [StyleType.STREETWEAR, StyleType.ATHLEISURE, StyleType.SMART_CASUAL], priceUsd: 110, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/outerwear/bomber.png", fitType: "regular", bodyTypeCompatibility: [BodyType.RECTANGLE, BodyType.APPLE, BodyType.INVERTED_TRIANGLE], material: "nylon", season: ["fall", "spring"], minimalAesthetic: false, genderExpression: GenderExpression.MASCULINE },
  { id: "out-004", name: "Cream Knit Cardigan", category: Category.OUTERWEAR, subcategory: "cardigan", colors: ["#FAF0E6"], dominantColor: "#FAF0E6", styles: [StyleType.MINIMALIST, StyleType.CLASSIC, StyleType.BOHEMIAN, StyleType.ROMANTIC], priceUsd: 72, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/outerwear/cardigan.png", fitType: "relaxed", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE], material: "cotton knit", season: ["fall", "winter", "spring"], minimalAesthetic: true, genderExpression: GenderExpression.FEMININE },

  // === SHOES ===
  { id: "sho-001", name: "White Leather Sneakers", category: Category.SHOES, subcategory: "sneakers", colors: ["#FFFFFF"], dominantColor: "#FFFFFF", styles: [StyleType.MINIMALIST, StyleType.STREETWEAR, StyleType.SMART_CASUAL, StyleType.ATHLEISURE], priceUsd: 95, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/shoes/sneakers.png", fitType: "regular", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "leather", season: ["spring", "summer", "fall"], minimalAesthetic: true, genderExpression: GenderExpression.NEUTRAL },
  { id: "sho-002", name: "Black Chelsea Boots", category: Category.SHOES, subcategory: "chelsea-boots", colors: ["#1A1A1A"], dominantColor: "#1A1A1A", styles: [StyleType.CLASSIC, StyleType.EDGY, StyleType.MINIMALIST, StyleType.SMART_CASUAL], priceUsd: 145, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/shoes/chelsea-boots.png", fitType: "regular", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "leather", season: ["fall", "winter", "spring"], minimalAesthetic: true, genderExpression: GenderExpression.NEUTRAL },
  { id: "sho-003", name: "Tan Suede Loafers", category: Category.SHOES, subcategory: "loafers", colors: ["#D2B48C"], dominantColor: "#D2B48C", styles: [StyleType.CLASSIC, StyleType.PREPPY, StyleType.SMART_CASUAL], priceUsd: 120, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/shoes/loafers.png", fitType: "regular", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "suede", season: ["spring", "summer", "fall"], minimalAesthetic: true, genderExpression: GenderExpression.NEUTRAL },
  { id: "sho-004", name: "Nude Block Heel Sandals", category: Category.SHOES, subcategory: "sandals", colors: ["#E8C9A0"], dominantColor: "#E8C9A0", styles: [StyleType.CLASSIC, StyleType.ROMANTIC, StyleType.SMART_CASUAL], priceUsd: 85, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/shoes/sandals.png", fitType: "regular", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "faux leather", season: ["spring", "summer"], minimalAesthetic: true, genderExpression: GenderExpression.FEMININE },
  { id: "sho-005", name: "High-Top Canvas Sneakers", category: Category.SHOES, subcategory: "high-tops", colors: ["#2F4F4F"], dominantColor: "#2F4F4F", styles: [StyleType.STREETWEAR, StyleType.VINTAGE, StyleType.EDGY], priceUsd: 65, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/shoes/high-tops.png", fitType: "regular", bodyTypeCompatibility: [BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE, BodyType.HOURGLASS], material: "canvas", season: ["spring", "summer", "fall"], minimalAesthetic: false, genderExpression: GenderExpression.NEUTRAL },

  // === SOCKS ===
  { id: "sok-001", name: "Navy Ribbed Dress Socks", category: Category.SOCKS, subcategory: "dress-socks", colors: ["#1B3A5C"], dominantColor: "#1B3A5C", styles: [StyleType.CLASSIC, StyleType.SMART_CASUAL, StyleType.PREPPY], priceUsd: 12, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/socks/dress-socks.png", fitType: "regular", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "cotton blend", season: ["spring", "summer", "fall", "winter"], minimalAesthetic: true, genderExpression: GenderExpression.NEUTRAL },
  { id: "sok-002", name: "Patterned Crew Socks", category: Category.SOCKS, subcategory: "crew-socks", colors: ["#FF6347", "#FFD700", "#4169E1"], dominantColor: "#FF6347", styles: [StyleType.STREETWEAR, StyleType.VINTAGE, StyleType.PREPPY], priceUsd: 15, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/socks/crew-socks.png", fitType: "regular", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "cotton", season: ["spring", "summer", "fall", "winter"], minimalAesthetic: false, genderExpression: GenderExpression.NEUTRAL },
  { id: "sok-003", name: "Black No-Show Socks", category: Category.SOCKS, subcategory: "no-show", colors: ["#1A1A1A"], dominantColor: "#1A1A1A", styles: [StyleType.MINIMALIST, StyleType.SMART_CASUAL, StyleType.ATHLEISURE], priceUsd: 10, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/socks/no-show.png", fitType: "regular", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "cotton blend", season: ["spring", "summer", "fall", "winter"], minimalAesthetic: true, genderExpression: GenderExpression.NEUTRAL },
  { id: "sok-004", name: "Sheer Ankle Socks", category: Category.SOCKS, subcategory: "ankle-socks", colors: ["#F5DEB3"], dominantColor: "#F5DEB3", styles: [StyleType.ROMANTIC, StyleType.CLASSIC, StyleType.VINTAGE], priceUsd: 14, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/socks/ankle-socks.png", fitType: "regular", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "nylon", season: ["spring", "summer"], minimalAesthetic: true, genderExpression: GenderExpression.FEMININE },

  // === BAGS ===
  { id: "bag-001", name: "Black Leather Tote", category: Category.BAG, subcategory: "tote", colors: ["#1A1A1A"], dominantColor: "#1A1A1A", styles: [StyleType.CLASSIC, StyleType.MINIMALIST, StyleType.SMART_CASUAL], priceUsd: 120, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/bags/tote.png", fitType: "structured", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "leather", season: ["spring", "summer", "fall", "winter"], minimalAesthetic: true, genderExpression: GenderExpression.FEMININE },
  { id: "bag-002", name: "Canvas Crossbody Bag", category: Category.BAG, subcategory: "crossbody", colors: ["#556B2F", "#D2B48C"], dominantColor: "#556B2F", styles: [StyleType.BOHEMIAN, StyleType.STREETWEAR, StyleType.ATHLEISURE], priceUsd: 45, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/bags/crossbody.png", fitType: "relaxed", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "canvas", season: ["spring", "summer", "fall"], minimalAesthetic: false, genderExpression: GenderExpression.NEUTRAL },
  { id: "bag-003", name: "Minimalist Leather Backpack", category: Category.BAG, subcategory: "backpack", colors: ["#8B7355"], dominantColor: "#8B7355", styles: [StyleType.MINIMALIST, StyleType.SMART_CASUAL, StyleType.STREETWEAR], priceUsd: 95, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/bags/backpack.png", fitType: "structured", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "leather", season: ["spring", "summer", "fall", "winter"], minimalAesthetic: true, genderExpression: GenderExpression.NEUTRAL },

  // === JEWELRY ===
  { id: "jwl-001", name: "Gold Chain Necklace", category: Category.JEWELRY, subcategory: "necklace", colors: ["#FFD700"], dominantColor: "#FFD700", styles: [StyleType.CLASSIC, StyleType.ROMANTIC, StyleType.STREETWEAR, StyleType.EDGY], priceUsd: 35, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/jewelry/necklace.png", fitType: "regular", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "gold-plated", season: ["spring", "summer", "fall", "winter"], minimalAesthetic: false, genderExpression: GenderExpression.NEUTRAL },
  { id: "jwl-002", name: "Silver Minimalist Cuff", category: Category.JEWELRY, subcategory: "bracelet", colors: ["#C0C0C0"], dominantColor: "#C0C0C0", styles: [StyleType.MINIMALIST, StyleType.CLASSIC, StyleType.EDGY], priceUsd: 28, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/jewelry/bracelet.png", fitType: "regular", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "sterling silver", season: ["spring", "summer", "fall", "winter"], minimalAesthetic: true, genderExpression: GenderExpression.NEUTRAL },
  { id: "jwl-003", name: "Pearl Stud Earrings", category: Category.JEWELRY, subcategory: "earrings", colors: ["#FDEBD0"], dominantColor: "#FDEBD0", styles: [StyleType.CLASSIC, StyleType.ROMANTIC, StyleType.PREPPY, StyleType.MINIMALIST], priceUsd: 22, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/jewelry/earrings.png", fitType: "regular", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "faux pearl", season: ["spring", "summer", "fall", "winter"], minimalAesthetic: true, genderExpression: GenderExpression.FEMININE },
  { id: "jwl-004", name: "Layered Ring Set", category: Category.JEWELRY, subcategory: "rings", colors: ["#FFD700", "#C0C0C0"], dominantColor: "#FFD700", styles: [StyleType.BOHEMIAN, StyleType.ROMANTIC, StyleType.VINTAGE], priceUsd: 18, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/jewelry/rings.png", fitType: "regular", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "mixed metals", season: ["spring", "summer", "fall", "winter"], minimalAesthetic: false, genderExpression: GenderExpression.NEUTRAL },

  // === HATS ===
  { id: "hat-001", name: "Black Wool Fedora", category: Category.HAT, subcategory: "fedora", colors: ["#1A1A1A"], dominantColor: "#1A1A1A", styles: [StyleType.CLASSIC, StyleType.BOHEMIAN, StyleType.EDGY], priceUsd: 45, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/hats/fedora.png", fitType: "regular", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "wool", season: ["fall", "winter"], minimalAesthetic: true, genderExpression: GenderExpression.NEUTRAL },
  { id: "hat-002", name: "Baseball Cap", category: Category.HAT, subcategory: "cap", colors: ["#1B3A5C"], dominantColor: "#1B3A5C", styles: [StyleType.STREETWEAR, StyleType.ATHLEISURE], priceUsd: 25, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/hats/cap.png", fitType: "regular", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "cotton", season: ["spring", "summer"], minimalAesthetic: false, genderExpression: GenderExpression.NEUTRAL },

  // === SCARVES ===
  { id: "scf-001", name: "Cashmere Wrap Scarf", category: Category.SCARF, subcategory: "wrap", colors: ["#C19A6B", "#FAF0E6"], dominantColor: "#C19A6B", styles: [StyleType.CLASSIC, StyleType.MINIMALIST, StyleType.ROMANTIC], priceUsd: 65, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/scarves/wrap.png", fitType: "regular", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "cashmere blend", season: ["fall", "winter"], minimalAesthetic: true, genderExpression: GenderExpression.NEUTRAL },
  { id: "scf-002", name: "Silk Print Scarf", category: Category.SCARF, subcategory: "silk-scarf", colors: ["#E8A0BF", "#4A90D9", "#FFD700"], dominantColor: "#E8A0BF", styles: [StyleType.CLASSIC, StyleType.ROMANTIC, StyleType.BOHEMIAN, StyleType.VINTAGE], priceUsd: 40, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/scarves/silk-scarf.png", fitType: "regular", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "silk", season: ["spring", "summer", "fall"], minimalAesthetic: false, genderExpression: GenderExpression.FEMININE },

  // === BELTS ===
  { id: "blt-001", name: "Brown Leather Belt", category: Category.BELT, subcategory: "leather-belt", colors: ["#8B4513"], dominantColor: "#8B4513", styles: [StyleType.CLASSIC, StyleType.SMART_CASUAL, StyleType.PREPPY], priceUsd: 35, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/belts/leather-belt.png", fitType: "regular", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "leather", season: ["spring", "summer", "fall", "winter"], minimalAesthetic: true, genderExpression: GenderExpression.NEUTRAL },
  { id: "blt-002", name: "Chain Detail Belt", category: Category.BELT, subcategory: "chain-belt", colors: ["#FFD700", "#1A1A1A"], dominantColor: "#FFD700", styles: [StyleType.EDGY, StyleType.STREETWEAR, StyleType.VINTAGE], priceUsd: 30, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/belts/chain-belt.png", fitType: "regular", bodyTypeCompatibility: [BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.PEAR], material: "metal/leather", season: ["spring", "summer", "fall", "winter"], minimalAesthetic: false, genderExpression: GenderExpression.FEMININE },

  // === SUNGLASSES ===
  { id: "sun-001", name: "Classic Aviator Sunglasses", category: Category.SUNGLASSES, subcategory: "aviator", colors: ["#FFD700", "#1A1A1A"], dominantColor: "#FFD700", styles: [StyleType.CLASSIC, StyleType.SMART_CASUAL, StyleType.VINTAGE], priceUsd: 55, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/sunglasses/aviator.png", fitType: "regular", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "metal/glass", season: ["spring", "summer"], minimalAesthetic: true, genderExpression: GenderExpression.NEUTRAL },
  { id: "sun-002", name: "Oversized Square Sunglasses", category: Category.SUNGLASSES, subcategory: "square", colors: ["#1A1A1A"], dominantColor: "#1A1A1A", styles: [StyleType.EDGY, StyleType.STREETWEAR, StyleType.BOHEMIAN], priceUsd: 40, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/sunglasses/square.png", fitType: "regular", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "acetate", season: ["spring", "summer"], minimalAesthetic: false, genderExpression: GenderExpression.FEMININE },

  // === WATCHES ===
  { id: "wtc-001", name: "Minimalist Silver Watch", category: Category.WATCH, subcategory: "analog", colors: ["#C0C0C0", "#FFFFFF"], dominantColor: "#C0C0C0", styles: [StyleType.MINIMALIST, StyleType.CLASSIC, StyleType.SMART_CASUAL], priceUsd: 85, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/watches/analog.png", fitType: "regular", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "stainless steel", season: ["spring", "summer", "fall", "winter"], minimalAesthetic: true, genderExpression: GenderExpression.NEUTRAL },
  { id: "wtc-002", name: "Gold Digital Watch", category: Category.WATCH, subcategory: "digital", colors: ["#FFD700"], dominantColor: "#FFD700", styles: [StyleType.VINTAGE, StyleType.STREETWEAR, StyleType.EDGY], priceUsd: 60, retailer: "Mock Store", productUrl: "#", imageUrl: "/items/watches/digital.png", fitType: "regular", bodyTypeCompatibility: [BodyType.APPLE, BodyType.PEAR, BodyType.HOURGLASS, BodyType.RECTANGLE, BodyType.INVERTED_TRIANGLE], material: "stainless steel", season: ["spring", "summer", "fall", "winter"], minimalAesthetic: false, genderExpression: GenderExpression.NEUTRAL },
];
